### ISSUE TITLE
[Bug]: pyRevit 5 Installer does not remove bin from path

### ISSUE THREAD

**Issue by TPJW** [pyrevitlabs/pyRevit#2406] opened 2024-09-24 22:24 UTC
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

When running the uninstaller for pyRevit 5.0.0.24255, I notice that the path to bin is still left on my system environment variables after the uninstaller is complete.

### ⌨ Error/Debug Message

```shell
NA
```

### ♻️ To Reproduce

1. Run pyRevit 5.0.0.24255 WIP installer
> The current WIP release should also be fine
2. Verify that ``C:\Program Files\pyRevit-5.0.0.24255\bin`` is on the system environment variables for ``Path``
> Side note: I'm used to that being ``PATH`` on other computers, although for me its ``Path`` - I'm curious as to if that is a potential problem point
3. Run uninstaller though the windows "add or remove" window
4. Check to see if ``C:\Program Files\pyRevit-5.0.0.24255\bin`` remains on ``Path`` for system environment variables

### ⏲️ Expected behavior

``C:\Program Files\pyRevit-5.0.0.24255\bin`` is removed from Path in environment variables

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
V4 | Deploy: "basepublic" | Branch: "master" | Version: "4.8.16" | Path: "C:\pyRevit\main"
==> Attachments
==> Installed Extensions
==> Default Extension Search Path
C:\Users\TPJW\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/pyrevitlabs/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2025 | Version: 25.0.2.419 | Build: 20240307_1300(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2025\"
Autodesk Revit 2023 | Version: 23.1.50.23 | Build: 20240709_1030(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023\"
Autodesk Revit 2022 | Version: 22.1.70.9 | Build: 20240704_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022\"
2021.1.7 | Version: 21.1.70.21 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2021\"
2020.2.9 | Version: 20.2.90.12 | Build: 20220517_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2020\"
==> Running Revit Instances
==> User Environment
Microsoft Windows 10 [Version 10.0.22631]
Executing User: TP\TPJW
Active User: TP\TPJW
Admin Access: Yes
%APPDATA%: "C:\Users\TPJW\AppData\Roaming"
Latest Installed .Net Framework: 4.8
Installed .Net Target Packs: v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.6.2 v4.7 v4.7.1 v4.7.2 v4.8 v4.8.1 v4.X
Installed .Net-Core Target Packs: v2.1.202 v7.0.400
pyRevit CLI v4.8.16.24121+2117.23a0b8cbc4babdeb29a0611e159d017bbe9cbad5
```

### Additional context

Actual OS is Windows 11 Enterprise, version 23H2

_Side note: I'm not quite sure if we should be filing issues on WIP releases - apologies if thats not proper procedure_

**Comment by sanzoghenzo** [comment] 2024-09-25 05:44
Duplicate of #1928

**Closed by sanzoghenzo** 2024-09-25 05:44 UTC
Labels: Bug
