### ISSUE TITLE
Balloon forms in lieu of toast (due to pyRevit 5)

### ISSUE THREAD

**Issue by aussieBIMguru** [pyrevitlabs/pyRevit#2352] opened 2024-08-16 05:13 UTC
Looks like the toast got burnt in pyRevit5!

Just leaving this here if it helps. I noticed in pyRevit 5 toast forms do not seem to trigger. From what I understand of the toast form it depends on another code library packaged into pyRevit that I suspect isn't netcore compatible.

I found the windows balloonforms work and can generate a pretty similar outcome, maybe below code might help the team if the toast form is difficult to reimplement. The main drawback is it's a bit less pretty and doesn't support the dictionary list for buttons like toast did.

The on click function is a bit rudimentary that I've built - attempts to support filepath/urlpath open on clicking the form generally vs giving the user extra buttons with tooltip to describe this being the behavior of doing so.

```
import clr
import os
import webbrowser
clr.AddReference('System.Windows.Forms')
clr.AddReference('System.Drawing')
import System
from System.Windows.Forms import Application, ToolTipIcon, NotifyIcon

class formUtils_balloonMessage:
    def __init__(self, title, msg, warnIcon = False, filePath = None, urlPath = None):
        self.title = title
        self.msg = msg
        self.filePath = filePath
        self.urlPath = urlPath
        if warnIcon:
            self.icon = ToolTipIcon.Warning
        else:
            self.icon = ToolTipIcon.Info
    def show(self):
        balloonMessage = NotifyIcon()
        if self.filePath is not None or self.urlPath is not None:
            balloonMessage.BalloonTipClicked += self.onClick
        balloonMessage.Text = self.title
        balloonMessage.Visible = True
        balloonMessage.Icon = System.Drawing.Icon.ExtractAssociatedIcon(Application.ExecutablePath)
        balloonMessage.ShowBalloonTip(5000, self.title, self.msg, self.icon)
    def onClick(self, sender, args):
        if self.filePath is not None:
            try:
                os.startfile(self.filePath)
            except:
                pass
        elif self.urlPath is not None:
            try:
                webbrowser.open(self.urlPath)
            except:
                pass
```

**Comment by aussieBIMguru** [comment] 2024-08-16 05:23
Example of the appearance vs toast.

![image](https://github.com/user-attachments/assets/153c4aae-6bb6-4855-adac-6af32bc61a6a)

**Comment by jmcouffin** [comment] 2024-08-20 13:48
Is it possible this is not a bug @aussieBIMguru 
Toast notification can be deactivated in Windows (at least this is what I have done on my setup long ago)
https://answers.microsoft.com/en-us/windows/forum/all/windows-10-toast-notification/39677a5b-8a73-4c27-91fb-d377c5f04a4a

**Comment by aussieBIMguru** [comment] 2024-08-21 00:09
Yes in this case I've managed to get the toast forms triggering in lower versions on the same machine so I'm fairly sure it's pyRevit related. No errors trigger, it just doesn't show any toast notification when ran.

**Comment by sanzoghenzo** [comment] 2024-08-21 05:24
Thanks @aussieBIMguru for the code sample!
Some observations:

- why the new feature request instead of filing a bug to restore the toasts? Obviously we can do both: add balloons while trying to fix the toasts...
- since you already have something working, go ahead and do a PR adding this in the pyrevit library!
- classes should be PascalCase, socrename it to `BalloonMessage`
- methods, argument and variables should be snake_case, rename accordingly
- I'd name the argument `warning` instead of `warnIcon` and use a more concise `self.icon = ToolTipIcon.Warning if warning else ToolTipIcon.Info`
- to make it more general, use a `click_callback` argument in the `__init__` method in place of the `filePath` and `urlPath`, then in the `on_click` method just call `self.click_callback()` if it is not `None`.

And now that I get a better look at it, this could be turned into a function, no need to overengineer things! Just extract the `show` method and add the parameters there 😉

**Comment by aussieBIMguru** [comment] 2024-08-25 23:14
Thanks! I'm not overly familiar with the pyRevit conventions and PR system but will do some research and put something forward in the forms library once I've got my head around it. It does load in some windows libraries to support dependency which have a slight speed hit in my experience, but can't see how to avoid that.

**Comment by sanzoghenzo** [comment] 2024-08-26 05:12
There still are no pyRevit conventions per se, I just trying to enforce best practices in the python world, but I understand that, given the intersection between python and c#, there is some style mixup... for now the important thing is to be consistent within your code: there's no place for underscores when you use camelCase and PascalCase, as snake_case is all lowecase.

For the PR:

- fork this repository to you own github account
- clone you fork to your pc, either separately (easier) or adding it as a new remote in a local copy of 
- checkout the develop branch
- make the modifications
- commit (please use a meaningful message of what it does)
- push the commit to your fork
- in github, either in your repo or this one, you will see a banner that allows you to create a PR with the commit you just pushed.

Most of this can be done in Visual Studio Code, if you use that.

**Comment by aussieBIMguru** [comment] 2024-08-26 07:35
Yes that's moreso what I mean, need to spend some time figuring out the style of pyRevit. I've developed some habits (some good, some not) managing my own extension. Personally I use camel after snake for functions as I find myself needing multiple words to describe the function beyond the primary object but I'll look at this when time allows to put it into a closer style at the least.

I generally use pyCharm but am familiar with VS/git systems as of late. It'll likely be a ways off as just trying to get my company code working before I get back to this but will see how I go. Thanks for the tips!

**Comment by sanzoghenzo** [comment] 2024-10-19 15:22
I've found the problem with the toaster and made the PR (link above).

I believe that after this fix we don't need "balloons" (by the way, there's already a `pyrevit.forms.show_balloon` function that uses Revit's own notifications in the upper right corner), but if you need it a cleaned (but untested) version of your script would be:

```python
from pyrevit.framework import Forms, Drawing

def system_balloon(message, title, warning=False, click_callback=None):
    balloon = Forms.NotifyIcon()
    if click_callback is not None:
        balloon.BalloonTipClicked += click_callback
    balloon.Text = title
    balloon.Visible = True
    balloon.Icon = Drawing.Icon.ExtractAssociatedIcon(Forms.Application.ExecutablePath)
    icon = Forms.ToolTipIcon.Warning if warning else Forms.ToolTipIcon.Info
    balloon.ShowBalloonTip(5000, title, message, icon)
```

**Comment by jmcouffin** [comment] 2024-10-21 09:12
fixed by @2426

**Comment by jmcouffin** [comment] 2024-10-21 09:12
thanks @sanzoghenzo 
Good job again

**Closed by jmcouffin** 2024-10-21 09:12 UTC
Labels: New Feature, pyRevit 5
