### ISSUE TITLE
[Bug]: [Pyrevit5]: netfx error on versions earlier than 2025

### ISSUE THREAD

**Issue by tay0thman** [pyrevitlabs/pyRevit#2383] opened 2024-08-30 00:56 UTC
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

running 5.0.0.24242, introduce the error below on netfx versions (2023,2024) still works fine on 2025

![image](https://github.com/user-attachments/assets/a9236c73-f5c2-4dbe-917c-776ca5320d05)

installing an older build pyRevit_5.0.0.24235 seems to work fine, so likely the bug was introduced in the last couple of days and it is likely related to netfx.

### ⌨ Error/Debug Message

```shell
[Window Title]
PyRevitLoader - Error Loading pyRevit

[Main Instruction]
IronPython Traceback:
Traceback (most recent call last):
  File "C:\Program Files\pyRevit-Master\bin\netfx\engines\pyRevitLoader.py", line 33, in <module>
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\loader\sessionmgr.py", line 267, in load_session
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\loader\sessioninfo.py", line 70, in setup_runtime_vars
  File "C:\Program Files\pyRevit-Master\pyrevitlib\pyrevit\loader\sessioninfo.py", line 158, in set_loaded_pyrevit_referenced_modules
TypeError: sequence item 10: expected string, NoneType found

Script Executor Traceback:
IronPython.Runtime.Exceptions.TypeErrorException: sequence item 10: expected string, NoneType found
   at IronPython.Runtime.Operations.StringOps.AppendJoin(Object value, Int32 index, StringBuilder sb)
   at IronPython.Runtime.Operations.StringOps.join(String self, List sequence)
   at CallSite.Target(Closure , CallSite , CodeContext , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
   at PyRevitLoader.ScriptExecutor.ExecuteScript(String sourcePath, IEnumerable`1 sysPaths, String logFilePath, IDictionary`2 variables)

[Close]
```

### ♻️ To Reproduce

1. install the latest build of pyrevit pyRevit_5.0.0.24242
2. Start Revit 2023 or 2024
3. Pyrevit Error will show up

### ⏲️ Expected behavior

should run without errors

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Windows 11 + Revit 2023, 2024, 2025
```

**Comment by sanzoghenzo** [comment] 2024-08-30 05:06
Duplicate of #2375

**Closed by sanzoghenzo** 2024-08-30 05:06 UTC
Labels: Bug
